# incline angle
INCLINE_ANGLE_MIN = 20
INCLINE_ANGLE_GOOD_MIN = 27
INCLINE_ANGLE_GOOD_MAX = 48
INCLINE_ANGLE_MAX = 55

# elbow position (bottom of rep)
ELBOW_POSITION_MIN = 0.1
ELBOW_POSITION_GOOD_MIN = 0.15
ELBOW_POSITION_GOOD_MAX = 0.25
ELBOW_POSITION_MAX = 0.3

# forearm angle (bottom of rep)
FOREARM_ANGLE_MIN = 34
FOREARM_ANGLE_GOOD_MIN = 37
FOREARM_ANGLE_GOOD_MAX = 43
FOREARM_ANGLE_MAX = 46

# arm extension angle (top of rep)
ARM_EXTENSION_ANGLE_MIN = 130
ARM_EXTENSION_ANGLE_GOOD_MIN = 145
ARM_EXTENSION_ANGLE_GOOD_MAX = 170
ARM_EXTENSION_ANGLE_MAX = 185

# arm elevation angle (top of rep)
ARM_ELEVATION_ANGLE_MIN = 80
ARM_ELEVATION_ANGLE_GOOD_MIN = 90
ARM_ELEVATION_ANGLE_GOOD_MAX = 110
ARM_ELEVATION_ANGLE_MAX = 120