# incline angle
INCLINE_ANGLE_MIN = 20
INCLINE_ANGLE_GOOD_MIN = 27
INCLINE_ANGLE_GOOD_MAX = 48
INCLINE_ANGLE_MAX = 55

# arm extension angle
ARM_EXTENSION_ANGLE_MIN = 130
ARM_EXTENSION_ANGLE_GOOD_MIN = 145
ARM_EXTENSION_ANGLE_GOOD_MAX = 170
ARM_EXTENSION_ANGLE_MAX = 185

# arm elevation angle
ARM_ELEVATION_ANGLE_MIN = 80
ARM_ELEVATION_ANGLE_GOOD_MIN = 90
ARM_ELEVATION_ANGLE_GOOD_MAX = 110
ARM_ELEVATION_ANGLE_MAX = 120